name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: pip install .[dev]

      - name: Python Semantic Release
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Run the version bump, build, and push
          semantic-release version --no-vcs-release --no-changelog
          
          # Check if a new tag was created on this commit
          if [ "$(git tag --points-at HEAD)" ]; then
            echo "released=true" >> $GITHUB_OUTPUT
            echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          else
            echo "released=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Version ZIP
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        if: steps.semantic.outputs.released == 'true'
        run: python generator.py --zip --transfer

      - name: GitHub Release
        if: steps.semantic.outputs.released == 'true'
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        uses: softprops/action-gh-release@v2
        with:
          files: repository.verkurkie-*.zip
          tag_name: ${{ steps.semantic.outputs.tag }}
          generate_release_notes: true
